---
- apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - supervisor
    - npm
    - libxrandr-dev
    - libxcursor-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libfreeimage-dev

- name: update graphistry repo
  git: repo=git@github.com:lmeyerov/graphistry.git dest=/opt/graphistry version=master update=yes
  
- name: graphistry config
  template: src=config.j2 dest=/opt/graphistry/experiments/nbody/naive/config.js group=www owner=www

- name: update Superconductor repo
  git: repo=git@github.com:lmeyerov/Superconductor2.git dest=/opt/Superconductor2 version=master update=yes
  
- command: chown -R www:www /opt/Superconductor2
  sudo: yes
  
- command: chmod g+w -R /opt/Superconductor2
  sudo: yes

- command: chown -R www:www /opt/graphistry
  sudo: yes
  
- command: chmod g+w -R /opt/graphistry
  sudo: yes

- command: mkdir /home/www/.npm_global
  ignore_errors: true
  sudo: yes

- command: chown -R www:www /home/www/.npm_global
  sudo: yes
  
- command: chmod g+w -R /home/www/.npm_global
  sudo: yes

- command: npm config set prefix "/home/www/.npm_global"
  sudo: yes
  sudo_user: www

- command: npm install --global grunt-cli
  sudo: yes
  sudo_user: www

# AntTweakBar
# - command: chdir=/tmp/ wget -O 'AntTweakBar_116.zip' 'http://sourceforge.net/projects/anttweakbar/files/latest/download?source=dlp'
# - command: chdir=/tmp/ unzip AntTweakBar_116.zip
# - command: chdir=/tmp/AntTweakBar/src make
# - command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so /usr/lib/
#   sudo: yes
# - command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so.1 /usr/lib/
#   sudo: yes
# TODO: register changed and skip
# 
# GLFW
# - git: repo=git@github.com:glfw/glfw.git dest=/opt/glfw version=master update=yes
# - command: chdir=/opt/glfw cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=TRUE
# - command: chdir=/opt/glfw make install
#   sudo: yes
# TODO: Try running the cmake command without `-DCMAKE_INSTALL_PREFIX=/usr`, so `cmake -G "Unix Makefiles"  -DBUILD_SHARED_LIBS=TRUE`. You'll need to manually move `libglfw.so` and its pkg-config file after, but it should work.

- command: npm install --global node-gyp
  sudo: yes
  sudo_user: www

# No idea why these don't work, can't seem to get Ansible run-as-user correct
# - command: chdir=/home/www npm install node-webcl
#   sudo: yes
#   sudo_user: www
# 
# - command: chdir=/home/www npm install node-webgl
#   sudo: yes
#   sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl/compress npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl/scproxy npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl npm link ./compress
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl/GPUStreaming/demos/uber npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/nodecl/GPUStreaming/StreamGL npm install
  sudo: yes
  sudo_user: www
  
- command: chdir=/opt/Superconductor2/nodecl/GPUStreaming/StreamGL /home/www/.npm_global/bin/grunt
  sudo: yes
  sudo_user: www

- command: chdir=/opt/Superconductor2/superconductorjs npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/graphistry/experiments/nbody/naive npm install
  sudo: yes
  sudo_user: www

- command: chdir=/opt/graphistry/experiments/nbody/loader npm install
  sudo: yes
  sudo_user: www

- command: mkdir /var/log/node-server
  ignore_errors: true
  sudo: yes

- name: node supervisor
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/node-server.conf
  sudo: yes
  notify: update supervisor

- command: supervisorctl reload
  sudo: yes