---
- get_url: dest=/tmp/cuda-repo-ubuntu1404_6.5-14_amd64.deb url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: node-server 

- command: chdir=/tmp dpkg -i cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: node-server 

- name: update apt
  apt: update_cache=yes
  sudo: yes

- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - supervisor
    - npm
    - libxrandr-dev
    - libxcursor-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libfreeimage-dev
    - libxinerama-dev
    - xinput
    - libxi-dev
    - pkg-config
    - nvidia-340-dev
    - linux-image-extra-virtual
    - mesa-utils
    - cuda
    - ubuntu-drivers-common
    - nvidia-common
  tags: node-server

- command: nvidia-xconfig -a --use-display-device=None --virtual=1680x1050
  sudo: yes
  tags: node-server

- template: src=xorg.conf.j2 dest=/etc/X11/xorg.conf
  sudo: yes
  tags: node-server

- template: src=grub.j2 dest=/etc/default/grub
  sudo: yes
  tags: node-server
  
- command: update-grub
  sudo: yes
  tags: node-server

- git: repo=git@github.com:glfw/glfw.git dest=/opt/glfw version=master update=yes accept_hostkey=yes
  register: glfw
  tags: node-server

- command: chdir=/opt/glfw cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=TRUE
  when: glfw.changed
  sudo: yes
  tags: node-server

- command: chdir=/opt/glfw make
  when: glfw.changed
  sudo: yes
  tags: node-server

- command: chdir=/opt/glfw make install
  when: glfw.changed
  sudo: yes
  tags: node-server

- get_url: dest=/tmp/AntTweakBar_116.zip url=http://sourceforge.net/projects/anttweakbar/files/latest/download
  register: anttweak_downloaded
  tags: node-server

- command: chdir=/tmp/ unzip AntTweakBar_116.zip
  when: anttweak_downloaded.changed
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src make
  when: anttweak_downloaded.changed
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so.1 /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: node-server

- name: update graphistry repo
  git: repo=git@github.com:lmeyerov/graphistry.git dest=/opt/graphistry version=master update=yes accept_hostkey=yes
  tags: node-server

- name: update Superconductor repo
  git: repo=git@github.com:lmeyerov/Superconductor2.git dest=/opt/Superconductor2 version=master update=yes accept_hostkey=yes
  tags: node-server
  
- command: chown -R www:www /opt/Superconductor2
  sudo: yes
  tags: node-server
  
- command: chmod g+w -R /opt/Superconductor2
  sudo: yes
  tags: node-server

- command: chown -R www:www /opt/graphistry
  sudo: yes
  tags: node-server
  
- command: chmod g+w -R /opt/graphistry
  sudo: yes
  tags: node-server

- command: mkdir /home/www/.npm_global
  ignore_errors: true
  sudo: yes
  tags: node-server

- command: chown -R www:www /home/www/.npm_global
  sudo: yes
  tags: node-server
  
- command: chmod g+w -R /home/www/.npm_global
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "npm config set prefix '/home/www/.npm_global'"
  sudo: yes
  tags: node-server

- command: npm install --global grunt-cli
  sudo: yes
  sudo_user: www
  tags: node-server

- command: npm install --global node-gyp
  sudo: yes
  sudo_user: root
  tags: node-server

# TODO: Fix this. Not sure what's up with Ansible's users.
- shell: sudo su www -l -c "cd /home/www && npm install node-webcl"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /home/www && npm install node-webgl"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/compress && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/scproxy && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl && npm link ./compress"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl && npm install"
  sudo: yes
  tags: node-server
  
- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/GPUStreaming/demos/libraries/bootstrap-slider && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/GPUStreaming/demos/libraries/bootstrap-slider && grunt"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/GPUStreaming/StreamGL && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/superconductorjs && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/GPUStreaming/demos/uber/js/ && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/Superconductor2/nodecl/GPUStreaming/StreamGL && grunt"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/graphistry/experiments/nbody/naive && npm install"
  sudo: yes
  tags: node-server

- shell: sudo su www -l -c "cd /opt/graphistry/experiments/nbody/loader && npm install"
  sudo: yes
  tags: node-server

- name: graphistry config
  template: src=config.j2 dest=/opt/graphistry/experiments/nbody/naive/config.js group=www owner=www
  sudo: yes
  tags: node-server

- command: mkdir /var/log/node-server
  ignore_errors: true
  sudo: yes
  tags: node-server

- name: remove all old supervisor configs to prevent drift
  shell: rm /etc/supervisor/conf.d/*
  sudo: yes
  ignore_errors: true
  tags: node-server

- name: node supervisor
  template: src=node-server.supervisor.j2 dest=/etc/supervisor/conf.d/node-server-{{ item.listen_port }}.conf
  with_items:
    - { listen_port: 10000 }
    - { listen_port: 10001 }
    - { listen_port: 10002 }
    - { listen_port: 10003 }
    - { listen_port: 10004 }
    - { listen_port: 10005 }
    - { listen_port: 10006 }
    - { listen_port: 10007 }
  sudo: yes
  notify: update supervisor
  tags: node-server

- name: add monitoring agent
  template: src=monitor.py.j2 dest=/opt/monitor.py
  sudo: yes
  tags: node-server

- name: monitoring supervisor
  template: src=monitor.supervisor.j2 dest=/etc/supervisor/conf.d/monitor.conf
  sudo: yes
  notify: update supervisor
  tags: node-server

- command: supervisorctl reload
  sudo: yes
  tags: node-server