---
- get_url: dest=/tmp/cuda-repo-ubuntu1404_6.5-14_amd64.deb url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: node-server-reboot 

- command: chdir=/tmp dpkg -i cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: node-server-reboot

- command: apt-get update
  sudo: yes
  tags: node-server-reboot

- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - nvidia-340-dev
    - linux-image-extra-virtual
    - mesa-utils
    - supervisor
    - npm
    - libxrandr-dev
    - libxcursor-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libfreeimage-dev
    - pkg-config
  tags: node-server-reboot

- command: nvidia-xconfig -a --use-display-device=None --virtual=1680x1050
  sudo: yes
  tags: node-server-reboot

- template: src=xorg.conf.j2 dest=/etc/X11/xorg.conf
  sudo: yes
  tags: node-server-reboot

- template: src=grub.j2 dest=/etc/default/grub
  sudo: yes
  tags: node-server-reboot
  
- command: update-grub
  sudo: yes
  tags: node-server-reboot
  
- command: reboot
  sudo: yes
  tags: node-server-reboot
  
- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - cuda
    - libxinerama-dev
    - xinput
    - libxi-dev
    - cmake
    - unzip
    - pigz
  tags: node-server

- git: repo=git@github.com:glfw/glfw.git dest=/tmp/glfw version=master update=yes accept_hostkey=yes
  tags: node-server

- command: chdir=/tmp/glfw cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=TRUE
  sudo: yes
  tags: node-server

- command: chdir=/tmp/glfw make
  sudo: yes
  tags: node-server

- command: chdir=/tmp/glfw make install
  sudo: yes
  tags: node-server

- get_url: dest=/tmp/AntTweakBar_116.zip url=http://sourceforge.net/projects/anttweakbar/files/latest/download
  sudo: yes
  register: anttweak_downloaded
  tags: node-server

- shell: cd /tmp && unzip AntTweakBar_116.zip
  sudo: yes
  when: anttweak_downloaded.changed
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src make
  sudo: yes
  when: anttweak_downloaded.changed
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: node-server

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so.1 /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: node-server
  
- command: mkdir /tmp/web
  ignore_errors: true
  tags:
  - node-server
  - node-server-fast

- command: chown -R ubuntu:ubuntu /tmp/web
  sudo: yes
  tags:
  - node-server
  - node-server-fast

- shell: npm config set prefix '/home/ubuntu/.npm_global'
  tags: 
    - node-server
    - node-server-fast    

- git: repo=git@github.com:graphistry/viz-server.git dest=/tmp/web/viz-server version=master update=yes accept_hostkey=yes
  tags: 
    - node-server
    - node-server-fast

- command: npm install --global grunt-cli
  tags: 
    - node-server
    - node-server-fast

- command: npm install --global node-gyp
  tags: 
    - node-server
    - node-server-fast

# TODO: Fix this. Not sure what's up with Ansible's users.
- shell: sudo su www -l -c "cd /home/www && npm install node-webcl"
  sudo: yes
  tags: 
    - node-server

- shell: sudo su www -l -c "cd /home/www && npm install node-webgl"
  sudo: yes
  tags: 
    - node-server

- shell: chdir=/home/ubuntu/ npm install node-webcl
  tags: 
    - node-server
    - node-server-fast

- shell: chdir=/home/ubuntu/ npm install node-webgl
  tags: 
    - node-server
    - node-server-fast

- shell: chdir=/tmp/web/viz-server npm install
  tags: 
    - node-server
    - node-server-fast

- command: cp -r /tmp/web/viz-server /opt
  sudo: yes
  tags: 
    - node-server
    - node-server-fast

- command: chown -R www:www /opt/
  sudo: yes
  tags: 
    - node-server
    - node-server-fast

- command: chmod g+w -R /opt/
  sudo: yes
  tags: 
    - node-server
    - node-server-fast

- name: graphistry config
  template: src=config.j2 dest=/opt/viz-server/config.js group=www owner=www
  sudo: yes
  when: production == true
  tags: 
    - node-server
    - node-server-fast

- command: mkdir /var/log/node-server
  ignore_errors: true
  sudo: yes
  tags: node-server

- name: remove all old supervisor configs to prevent drift
  shell: rm /etc/supervisor/conf.d/*
  sudo: yes
  ignore_errors: true
  tags: node-server

- name: node supervisor
  template: src=node-server.supervisor.j2 dest=/etc/supervisor/conf.d/node-server-{{ item.listen_port }}.conf
  with_items:
    - { listen_port: 10000 }
    - { listen_port: 10001 }
    - { listen_port: 10002 }
    - { listen_port: 10003 }
    - { listen_port: 10004 }
    - { listen_port: 10005 }
    - { listen_port: 10006 }
    - { listen_port: 10007 }
  sudo: yes
  notify: update supervisor
  tags: node-server

- name: add monitoring agent
  template: src=reaper.py.j2 dest=/opt/reaper.py
  sudo: yes
  when: production == true
  tags:
    - node-server
    - reaper

- name: monitoring supervisor
  template: src=reaper.supervisor.j2 dest=/etc/supervisor/conf.d/reaper.conf
  sudo: yes
  when: production == true
  notify: update supervisor
  tags:
    - node-server
    - reaper

- command: supervisorctl reload
  sudo: yes
  tags:
    - node-server
    - reaper
    - node-server-fast