language: python
cache: pip
python:
- 2.7.13
- 3.6
install:
- pip install flake8 pytest pyopenssl
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,pandas numpy pandas
- sudo add-apt-repository ppa:igraph/ppa -y
- sudo apt-get update -q
- sudo apt-get install python-igraph -y
- if [[ $TRAVIS_PYTHON_VERSION == 2.7.13 ]]; then pip install IPython==5.0; fi
- python setup.py install
before_script:
    # stop the build if there are Python syntax errors or undefined names
- time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
- time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
- python setup.py test
notifications:
  on_success: change
  on_failure: always
deploy:
  provider: pypi
  skip_existing: true
  on:
    tags: true
  user: graphistryAccount
  password:
    secure: J+DhdQduKVa7lw16Fc5Zy2h50gwPECF50QjFCRnKvdnicJ9nSJdjPQqrs2IcaEkh0GNcJzaWsLz9ImvszZnu9OrFe33jxMQw9DWra1H7lUnqEm830VoEQBWZOlR0gYA3idmI16HDezWn1XkUnkORcB2bFmaFiloT5KDJnOVUQK8xZiE/8/Ow+d1GKB8ME6UtlpH1oev+EXHnyFPrfwtAej7H5BbV3mlRB3oiSrKiFHHXj8GugO+YAcIffyUmE4XuXx2eVZZKT8sqAONxr4/LpOyreOYbD3YLENOFaZg0qrEMV7nhysC+vD5ueso8gdzrrlptDNFUnfNNe8IvAmVXuWGQhqdy9NKgAh3Koxzh+0A61OaoGoTrNbqUYvr+rUwiUZbdJNk4vGGCBpS6vABJX/wmnH2R6YA9JuyvElVXP31mW/N2QvMLr7cj9jkQA7O4EgnsFA853aI/ObWdWfdGT8lndNVs+RihJsUQOyrePLBXZBwlCPAKS8BfrE0JHSeCsba7Zrzw2vu9p4MqEpCyzmziijGhI9Jl9SmhHoGmaBLeDfnsJ8k6ULe3JrcbmbzLamy3w7p6CeFpbwrLhpTrM9mP667HMNbhoT5bM02bwll+i5vRufzIC3yU91EEayiwcCWSXrOjoUZNLVRYR8G2vL9ni9MjwBj8Delx+oIGOr8=
