version: '3'
services:
  jupyter:
    image: graphistry/jupyter-notebook
    volumes:
      - $PWD:/home/jovyan/
    environment:
      - JUPYTER_TOKEN=graphistry
    ports:
      - 8888:8888
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/pygraphistry
networks:
  default:
    external:
      name: compose_grph_net
    