---
- group: name={{ user }} state=present
  sudo: yes

- user: name={{ user }} groups="www" state=present
  sudo: yes

- synchronize: src=bash_profile dest=/home/{{ user }}/.bash_profile
  sudo: yes

- synchronize: src=bashrc dest=/home/{{ user }}/.bashrc
  sudo: yes

- command: chown -R www:www /home/{{ user }}/.bash_profile
  sudo: yes

- command: chmod g+w -R /home/{{ user }}/.bash_profile
  sudo: yes
  
- command: mkdir /home/www/.npm_global
  ignore_errors: true
  sudo: yes

- command: chown -R www:www /home/www/.npm_global
  sudo: yes

- command: chmod g+w -R /home/www/.npm_global
  sudo: yes

- shell: sudo su www -l -c "npm config set prefix '/home/www/.npm_global'"
  sudo: yes
