---
- user: name={{ user }} groups="admin,www" state=present
  sudo: yes

- synchronize: rsync_path="sudo rsync" src=bash_profile dest=/home/{{ user }}/.bash_profile
  sudo: yes
  
- synchronize: rsync_path="sudo rsync" src=bashrc dest=/home/{{ user }}/.bashrc
  sudo: yes

- command: mkdir /home/{{ user }}/.npm_global
  ignore_errors: true
  sudo: yes

- command: chown -R {{ user }}:{{ user }} /home/{{ user }}
  sudo: yes

- command: chmod g+w -R /home/{{ user }}
  sudo: yes
