---
# ==== BEGIN PROD DEPLOY ====
- hosts: localhost
  roles:
    - { role: slack, msg: "starting prod deploy" }

- hosts: workers
  roles:
   - { role: astanway, user: astanway, tags: provision }
   - { role: leo, user: leo, tags: provision }
   - { role: www, user: www, tags: provision }
   - { role: ubuntu, user: ubuntu, tags: provision }
   - { role: thibaud, user: thibaud, tags: provision }
   - { role: common, tags: provision }
   - { role: worker,
       production: true,
       mongo_server: 'mongodb://graphistry:graphtheplanet@lighthouse.2.mongolayer.com:10048,lighthouse.3.mongolayer.com:10048/graphistry-prod',
       mongo_db: 'graphistry-prod',
       tags: prod-full
    }
  tags: workers

- hosts: central
  roles:
   - { role: astanway, user: astanway, tags: provision }
   - { role: leo, user: leo, tags: provision }
   - { role: www, user: www, tags: provision }
   - { role: ubuntu, user: ubuntu, tags: provision }
   - { role: thibaud, user: thibaud, tags: provision }
   - { role: common, tags: provision }
   - { role: central,
       production: true,
       mongo_server: 'mongodb://graphistry:graphtheplanet@lighthouse.2.mongolayer.com:10048,lighthouse.3.mongolayer.com:10048/graphistry-prod',
       mongo_db: 'graphistry-prod',
       tags: prod-full
    }
  tags: central
  
- hosts: localhost
  roles:
   - { role: slack, msg: "finished prod deploy: view at http://dev.graphistry.com/" }

# ==== END PROD DEPLOY ====

# ==== BEGIN STAGING DEPLOY ====
- hosts: staging
  roles:
   - { role: slack, msg: "starting staging deploy" }
   - { role: astanway, user: astanway, tags: provision }
   - { role: quinn, user: quinn, tags: provision }
   - { role: leo, user: leo, tags: provision }
   - { role: thibaud, user: thibaud, tags: provision }
   - { role: www, user: www, tags: provision }
   - { role: ubuntu, user: ubuntu, tags: provision }
   - { role: common, tags: provision }
   - { role: worker,
       production: true,
       mongo_server: 'mongodb://graphistry:graphtheplanet@lighthouse.2.mongolayer.com:10048,lighthouse.3.mongolayer.com:10048/graphistry-staging',
       mongo_db: 'graphistry-staging',
       tags: staging-full
    }
   - { role: central, 
       production: true,
       mongo_server: 'mongodb://graphistry:graphtheplanet@lighthouse.2.mongolayer.com:10048,lighthouse.3.mongolayer.com:10048/graphistry-staging',
       mongo_db: 'graphistry-staging',
       tags: staging-full
     }
   - { role: slack, msg: "finished staging deploy: view at http://54.183.155.35/" }
  tags: staging

# ==== END STAGING DEPLOY ====

- hosts: splunk
  roles:
   - { role: astanway, user: astanway, tags: provision }
   - { role: www, user: www, tags: provision }
   - { role: ubuntu, user: ubuntu, tags: provision }
   - { role: common, tags: provision }
  tags: splunk
  
# - hosts: localdev
#   roles:
#     - { role: www, user: www }
#     - { role: vagrant, user: vagrant }
#     - common
#     - { role: worker, production: false }
#     - { role: central, production: false }
#   tags: localdev
