---
- hosts: dev-streaming
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
   - node-server
  tags: dev-streaming

- hosts: dev-central
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
   - central
  tags: dev-central
