---
- hosts: workers
  roles:
   - { role: astanway, user: astanway }
   - { role: leo, user: leo }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - { role: thibaud, user: thibaud }
   - common
   - { role: worker, production: true }
  tags: workers

- hosts: central
  roles:
   - { role: astanway, user: astanway }
   - { role: leo, user: leo }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - { role: thibaud, user: thibaud }
   - common
   - { role: central, production: true }
  tags: central

- hosts: localdev
  roles:
    # - { role: www, user: www }
    # - { role: vagrant, user: vagrant }
    # - common
    # - { role: worker, production: false }
    # - { role: central, production: false }
  tags: localdev

# - hosts: prod-dev
#   roles:
#    - { role: astanway, user: astanway }
#    - { role: quinn, user: quinn }
#    - { role: www, user: www }
#    - { role: ubuntu, user: ubuntu }
#    - common
#    - { role: worker, production: false }
#    - { role: central, production: false }
#   tags: dev
  
- hosts: splunk
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
  tags: splunk