---
- hosts: workers
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
   - { role: node-server, production: true }
  tags: workers

- hosts: central
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
   - { role: central, production: true }
  tags: central

# if you run this, be sure to hard code the address of the machine in config.js LISTEN_ADDRESS. todo: fix that.
# - hosts: quinn-dev
#   roles:
#    - { role: astanway, user: astanway }
#    - { role: quinn, user: quinn }
#    - { role: www, user: www }
#    - { role: ubuntu, user: ubuntu }
#    - common
#    - { role: node-server, production: false }
#    - { role: central, production: false }
#   tags: quinn-dev
  
- hosts: splunk
  roles:
   - { role: astanway, user: astanway }
   - { role: www, user: www }
   - { role: ubuntu, user: ubuntu }
   - common
  tags: splunk