---
- command: rm /var/lib/apt/lists/lock
  sudo: yes
  ignore_errors: true

- command: rm /var/cache/apt/archives/lock
  sudo: yes
  ignore_errors: true

- command: dpkg --configure -a
  sudo: yes
  ignore_errors: true

- name: update apt
  apt: update_cache=yes
  sudo: yes

- name: install common tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - npm

- name: install pip stuff
  pip: name={{ item }}
  sudo: yes
  with_items:
    - setuptools
    - distribute
    
- name: check installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{node_version}}
  register: wanted_version_installed
  ignore_errors: True

- name: fetch node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: configure node
  shell: /usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1

- name: make node
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1

- name: make install node
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1
  sudo: yes
  
- name: opt dir to www group
  command: chown www:www /opt
  sudo: yes

- name: sshd config
  template: src=sshd_config dest=/etc/ssh/sshd_config
  sudo: yes
  notify: restart sshd