---
- command: hostname {{ hostname }}
  sudo: yes
  tags: common

- template: src=hostname.j2 dest=/etc/hostname
  sudo: yes
  tags: common

- template: src=hosts.j2 dest=/etc/hosts
  sudo: yes
  tags: common

- template: src=timezone.j2 dest=/etc/timezone owner=root group=root mode=0644
  sudo: yes
  tags: common

- command: rm /var/lib/apt/lists/lock
  sudo: yes
  ignore_errors: true
  tags: common

- command: rm /var/cache/apt/archives/lock
  sudo: yes
  ignore_errors: true
  tags: common

- command: dpkg --configure -a
  sudo: yes
  ignore_errors: true
  tags: common

- name: update apt
  apt: update_cache=yes
  sudo: yes
  tags: common

- name: install common tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - npm
    - unattended-upgrades
    - python-psutil
    - supervisor
    - ntp
  tags: common

- name: create apt auto-upgrades job configuration
  template: >
    src=auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644
  sudo: yes
  tags: common

- name: create unattended-upgrades configuration
  template: >
    src=unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644
  sudo: yes
  tags: common

- name: install pip stuff
  pip: name={{ item }}
  sudo: yes
  with_items:
    - setuptools
    - distribute
    - pymongo
  tags: common

- name: install splunk forwarder
  action: get_url url=http://www.splunk.com/page/download_track?file=6.2.0/universalforwarder/linux/splunkforwarder-6.2.0-237341-Linux-x86_64.tgz&ac=&wget=true&name=wget&platform=Linux&architecture=x86_64&version=6.2.0&product=splunk&typed=release dest=/tmp/
  sudo: yes
  register: splunk_downloaded
  tags:
    - common
    - splunk

- name: unpack splunk forwarder
  command: tar zxf /tmp/splunkforwarder-6.2.0-237341-Linux-x86_64.tgz  chdir=/opt
  when: splunk_downloaded.changed
  sudo: yes
  tags:
    - common
    - splunk

- name: start splunk
  command: ./splunk start --accept-license chdir=/opt/splunkforwarder/bin
  sudo: yes
  tags:
    - common
    - splunk

- name: make sure auto boot is on
  command: ./splunk enable boot-start  chdir=/opt/splunkforwarder/bin
  sudo: yes
  tags:
    - common
    - splunk

- name: splunk auth
  command: ./splunk edit user admin -password graphtheplanet -auth admin:changeme chdir=/opt/splunkforwarder/bin
  sudo: yes
  ignore_errors: true
  tags:
    - common
    - splunk

- name: splunk forwarder
  command: ./splunk add forward-server splunk.graphistry.com:9997 -auth admin:graphtheplanet chdir=/opt/splunkforwarder/bin
  ignore_errors: true
  sudo: yes
  tags:
    - common
    - splunk

- template: src=inputs.conf dest=/opt/splunkforwarder/etc/apps/SplunkUniversalForwarder/default
  sudo: yes
  tags:
    - common
    - splunk

- name: restart splunk
  command: service splunk restart
  sudo: yes
  tags:
    - common
    - splunk

- name: check installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{node_version}}
  register: wanted_version_installed
  ignore_errors: True
  tags: common

- name: fetch node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: wanted_version_installed.rc == 1
  tags: common

- name: unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: wanted_version_installed.rc == 1
  tags: common

- name: configure node
  shell: /usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1
  tags: common

- name: make node
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1
  tags: common

- name: make install node
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1
  sudo: yes
  tags: common

- name: sshd config
  template: src=sshd_config dest=/etc/ssh/sshd_config
  sudo: yes
  tags:
    - ssh
    - common

- command: service ssh restart
  sudo: yes
  tags:
    - ssh
    - common