---
# - command: hostname {{ hostname }}
#   sudo: yes
# 
# - template: src=hostname.j2 dest=/etc/hostname
#   sudo: yes
# 
# - template: src=hosts.j2 dest=/etc/hosts
#   sudo: yes
# 
- command: rm /var/lib/apt/lists/lock
  sudo: yes
  ignore_errors: true

- command: rm /var/cache/apt/archives/lock
  sudo: yes
  ignore_errors: true

- command: dpkg --configure -a
  sudo: yes
  ignore_errors: true

- name: update apt
  apt: update_cache=yes
  sudo: yes

- name: install common tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - npm
    - unattended-upgrades
    - python-psutil
    - supervisor

- name: create apt auto-upgrades job configuration
  template: >
    src=auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644
  sudo: yes

- name: create unattended-upgrades configuration
  template: >
    src=unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644
  sudo: yes

- name: install pip stuff
  pip: name={{ item }}
  sudo: yes
  with_items:
    - setuptools
    - distribute
    - pymongo
    
- name: check installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{node_version}}
  register: wanted_version_installed
  ignore_errors: True

- name: fetch node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: configure node
  shell: /usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1

- name: make node
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1

- name: make install node
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1
  sudo: yes
   
- name: opt dir to www group
  command: chown www:www /opt
  sudo: yes

- name: write perms
  command: chmod g+w -R /opt
  sudo: yes

- shell: sudo su www -l -c "npm config set prefix '/home/www/.npm_global'"
  sudo: yes

- name: sshd config
  template: src=sshd_config dest=/etc/ssh/sshd_config
  sudo: yes
  tags: ssh

- command: service ssh restart
  sudo: yes
  tags: ssh