---
- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  get_url: dest=/tmp/cuda-repo-ubuntu1404_6.5-14_amd64.deb url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: provision 

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  command: chdir=/tmp dpkg -i cuda-repo-ubuntu1404_6.5-14_amd64.deb
  sudo: yes
  tags: provision

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  command: apt-get update
  sudo: yes
  tags: provision

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - nvidia-340-dev
    - linux-image-extra-virtual
    - mesa-utils
    - npm
    - libxrandr-dev
    - libxcursor-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libfreeimage-dev
    - pkg-config
  tags: provision

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  command: nvidia-xconfig -a --use-display-device=None --virtual=1680x1050
  sudo: yes
  tags: provision

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  template: src=xorg.conf.j2 dest=/etc/X11/xorg.conf
  sudo: yes
  tags: provision

- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision
  template: src=grub.j2 dest=/etc/default/grub
  sudo: yes
  tags: provision
 
- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision 
  command: update-grub
  sudo: yes
  tags: provision
 
- name: WARNING - INSTALLING CUDA FROM SCRATCH AND REBOOTING. UNLESS THIS IS YOUR FIRST TIME PROVISIONING THIS MACHINE, YOU PROBABLY SHOULDN\'T BE DOING THIS. TRY PASSING --skip-tags provision 
  command: reboot
  sudo: yes
  tags: provision

- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - cuda
    - libxinerama-dev
    - xinput
    - libxi-dev
    - cmake
    - unzip
    - pigz
  tags: worker

- git: repo=git@github.com:glfw/glfw.git dest=/tmp/glfw version=master update=yes accept_hostkey=yes
  register: glfw
  tags: worker

- command: chdir=/tmp/glfw cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=TRUE
  sudo: yes
  when: glfw.changed
  tags: worker

- command: chdir=/tmp/glfw make
  sudo: yes
  when: glfw.changed
  tags: worker

- command: chdir=/tmp/glfw make install
  sudo: yes
  when: glfw.changed
  tags: worker

- get_url: dest=/tmp/AntTweakBar_116.zip url=http://sourceforge.net/projects/anttweakbar/files/latest/download
  sudo: yes
  register: anttweak_downloaded
  tags: worker

- shell: cd /tmp && unzip AntTweakBar_116.zip
  sudo: yes
  when: anttweak_downloaded.changed
  tags: worker

- command: chdir=/tmp/AntTweakBar/src make
  sudo: yes
  when: anttweak_downloaded.changed
  tags: worker

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: worker

- command: chdir=/tmp/AntTweakBar/src mv ../lib/libAntTweakBar.so.1 /usr/lib/
  when: anttweak_downloaded.changed
  sudo: yes
  tags: worker
  
- command: mkdir /tmp/web
  ignore_errors: true
  tags:
  - worker

- command: chown -R {{ ansible_ssh_user }}:{{ ansible_ssh_user }} /tmp/web
  sudo: yes
  tags:
  - worker

- shell: npm config set prefix '/home/{{ ansible_ssh_user }}/.npm_global'
  tags: 
    - worker

- git: repo=git@github.com:graphistry/viz-server.git dest=/tmp/web/viz-server version=master update=yes accept_hostkey=yes
  tags: 
    - worker
    - worker-fast

- command: npm install --global grunt-cli
  tags: 
    - worker

- command: npm install --global node-gyp
  tags: 
    - worker

# TODO: Fix this. Not sure what's up with Ansible's users.
- shell: sudo su www -l -c "cd /home/www && npm install node-webcl"
  sudo: yes
  tags: 
    - worker

- shell: sudo su www -l -c "cd /home/www && npm install node-webgl"
  sudo: yes
  tags: 
    - worker

- shell: chdir=/home/{{ ansible_ssh_user }}/ npm install node-webcl
  tags: 
    - worker

- shell: chdir=/home/{{ ansible_ssh_user }}/ npm install node-webgl
  tags: 
    - worker

- shell: chdir=/tmp/web/viz-server npm install
  tags: 
    - worker
    - worker-fast

- command: cp -r /tmp/web/viz-server /opt
  sudo: yes
  tags: 
    - worker
    - worker-fast

- command: chown -R www:www /opt/
  sudo: yes
  tags: 
    - worker
    - worker-fast

- command: chmod g+w -R /opt/
  sudo: yes
  tags: 
    - worker
    - worker-fast

# Todo: Ugh.
- template: src=config.j2 dest=/opt/viz-server/config.js group=www owner=www
  sudo: yes
  when: production == true
  tags: 
    - worker
    - worker-fast

- template: src=config.j2 dest=/opt/viz-server/node_modules/graph-viz/config.js group=www owner=www
  sudo: yes
  when: production == true
  tags: 
    - worker
    - worker-fast

- template: src=config.j2 dest=/opt/viz-server/node_modules/horizon-viz/src/server/config.js group=www owner=www
  sudo: yes
  when: production == true
  tags: 
    - worker
    - worker-fast      

- command: mkdir /var/log/worker
  ignore_errors: true
  sudo: yes
  tags: worker

# - name: remove all old supervisor configs to prevent drift
#   shell: rm /etc/supervisor/conf.d/*
#   sudo: yes
#   ignore_errors: true
#   tags: worker

- name: node supervisor
  template: src=worker.supervisor.j2 dest=/etc/supervisor/conf.d/worker-{{ item.listen_port }}.conf
  with_items:
    - { listen_port: 10000 }
    - { listen_port: 10001 }
    - { listen_port: 10002 }
    - { listen_port: 10003 }
    - { listen_port: 10004 }
    - { listen_port: 10005 }
    - { listen_port: 10006 }
    - { listen_port: 10007 }
  sudo: yes
  notify: update supervisor
  tags: 
    - worker
    - supervisor

- name: add monitoring agent
  template: src=reaper.py.j2 dest=/opt/reaper.py
  sudo: yes
  when: production == true
  tags:
    - worker
    - reaper

- name: monitoring supervisor
  template: src=reaper.supervisor.j2 dest=/etc/supervisor/conf.d/reaper.conf
  sudo: yes
  when: production == true
  notify: update supervisor
  tags:
    - worker
    - reaper
    - supervisor

- command: supervisorctl update
  sudo: yes
  tags:
    - worker
    - reaper
    - worker-fast
    - supervisor

- command: supervisorctl reload
  sudo: yes
  tags:
    - worker
    - reaper
    - worker-fast
    - supervisor