---
- user: name={{ user }} group=admin shell=/bin/bash
  sudo: yes

- command: mkdir /home/{{ user }}/.ssh creates=/home/{{ user }}/.ssh
  sudo: yes

- command: touch /home/{{ user }}/.ssh/authorized_keys owner={{ user }}
  sudo: yes

- name: authorized key for {{ user }}
  lineinfile: dest=/home/{{ user }}/.ssh/authorized_keys line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoIdzuUcgOwE0Rctlc5lkntUPqFhFUvhw9PTSfUzk6YILHpJcdISP1mABn1V2WgNZg1Mhzs6NDAmwnFpKPa0x5WwsqD/K7sZnkRsb7X8puTZBLqk/NnGcvr+yuDl8fjUDtLf9IC80YTnNYQ74G06UQdq19GJGMvCS9nxxFzSID2w6acvrG+0332NDlEL0e3VibkMH2aikrHr6BSuq1Bprf/T+N0YukdnTxyCfcgY8KXfiQ+1oAteRWi+QxrUf/2LAid5VsVlt394iN5PAdabwqyuSzCQaWyWQtTpIykb/qPiMUusqPPBpgkX0cezDcOXKnpiYMaTSt+kXiwG3Af+Ph lmeyerov@gmail.com"
  sudo: yes

- synchronize: src=bash_profile dest=/home/{{ user }}/.bash_profile
  sudo: yes
  
- name: perms
  command: chown -R {{ user }} /home/{{ user }}
  sudo: yes