---
- name: Create group 'www'
  group: name='www'
  sudo: true

- name: Create user 'www'
  user: name='www' groups='www' group='www' shell=/bin/bash
  sudo: true

- { include: configure_user.yml, sudo: yes, sudo_user: www, user: www, homedir: "/home/www" }