---
- name: update graphistry repo
  git: repo=git@github.com:lmeyerov/graphistry.git dest=/opt/graphistry version=master update=yes accept_hostkey=yes

- command: mkdir /var/log/central-app
  sudo: yes
  ignore_errors: true

- command: chown -R www:www /opt/graphistry
  sudo: yes

- command: chmod g+w -R /opt/graphistry
  sudo: yes

- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - nginx

- template: src=nginx.j2 dest=/etc/nginx/sites-enabled/default
  sudo: yes
  notify: restart nginx

- template: src=central-app.supervisor.j2 dest=/etc/supervisor/conf.d/central-app.conf
  sudo: yes
  notify: update supervisor

- command: supervisorctl reload
  sudo: yes