---
- shell: npm config set prefix '/home/{{ ansible_ssh_user }}/.npm_global'

- command: mkdir /tmp/web
  ignore_errors: true

- command: chown -R {{ ansible_ssh_user }}:{{ ansible_ssh_user }} /tmp/web
  sudo: yes

- name: update central repo
  git: repo=git@github.com:graphistry/central.git dest=/tmp/web/central version=master update=yes accept_hostkey=yes
  tags: 
    - fast

- shell: chdir=/tmp/web/central npm install
  tags: 
    - fast

- command: cp -r /tmp/web/central /opt
  sudo: yes
  tags: 
    - fast

- command: chown -R www:www /opt/
  sudo: yes
  tags: 
    - fast

- command: chmod g+w -R /opt/
  sudo: yes
  tags: 
    - fast

- command: mkdir /var/log/central-app
  sudo: yes
  ignore_errors: true

- apt: pkg={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - nginx

- template: src=nginx.j2 dest=/etc/nginx/sites-enabled/default
  sudo: yes
  notify: restart nginx

- template: src=central-app.supervisor.j2 dest=/etc/supervisor/conf.d/central-app.conf
  sudo: yes
  tags: 
    - fast
    - supervisor

# Ensure supervisord itself is running
- command: service supervisor start
  sudo: yes
  tags:
    - fast
    - supervisor
  ignore_errors: true

# Read in config changes
- command: supervisorctl reread
  sudo: yes
  tags:
    - fast
    - supervisor

# Reload supervisor processes
- command: supervisorctl reload
  sudo: yes
  tags:
    - fast
    - supervisor